excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- ProjectNameTests
- ProjectNameUITests

disabled_rules: # rule identifiers turned on by default to exclude from running
- type_name
